// 1.) Words to learn how to read for the kid.
// TODO: Later pull from JSON file

let words = [
  { word: "kitty", s1: "kit", s2: "ty"},
  { word: "cookie", s1: "cook", s2: "ie"},
  { word: "window", s1: "win", s2: "dow"},
  { word: "sunny", s1: "sun", s2: "ny"},
  { word: "zebra", s1: "zeb", s2: "ra"},
  { word: "monkey", s1: "mon", s2: "key"},
  { word: "garden", s1: "gar", s2: "den"},
  { word: "castle", s1: "cas", s2: "tle"},
  { word: "oven", s1: "ov", s2: "en"},
  { word: "rocket", s1: "rock", s2: "et"},
  { word: "mommy", s1: "mom", s2: "my"},
  { word: "apple", s1: "app", s2: "le"},
  { word: "daddy", s1: "dad", s2: "dy"},
  { word: "circle", s1: "cir", s2: "cle"},
  { word: "turtle", s1: "tur", s2: "tle"},
  { word: "carrot", s1: "car", s2: "rot"},
  { word: "basket", s1: "bas", s2: "ket"},
  { word: "blindfold", s1: "blind", s2: "fold"},
  { word: "absent", s1: "ab", s2: "sent"},
  { word: "seven", s1: "sev", s2: "en"},
  { word: "sister", s1: "sis", s2: "ter"},
  { word: "woman", s1: "wo", s2: "man"},
  { word: "frozen", s1: "fro", s2: "zen"},
  { word: "pancake", s1: "pan", s2: "cake"},
  { word: "garbage", s1: "gar", s2: "bage"},
  { word: "teacher", s1: "tea", s2: "cher"},
  { word: "rabbit", s1: "rab", s2: "bit"},
  { word: "mother", s1: "moth", s2: "er"},
  { word: "paper", s1: "pa", s2: "per"},
  { word: "cartoon", s1: "car", s2: "toon"},
  { word: "candy", s1: "can", s2: "dy"},
  { word: "pencil", s1: "pen", s2: "cil"},
  { word: "donate", s1: "don", s2: "ate"},
  { word: "spider", s1: "spi", s2: "der"},
  { word: "boxer", s1: "box", s2: "er"},
  { word: "ketchup", s1: "ket", s2: "chup"},
  { word: "tiger", s1: "ti", s2: "ger"},
  { word: "doctor", s1: "doc", s2: "tor"},
  { word: "glasses", s1: "glass", s2: "es"},
  { word: "necklace", s1: "nek", s2: "lace"},
  { word: "pocket", s1: "pock", s2: "et"},
  { word: "cowboy", s1: "cow", s2: "boy"},
  { word: "baseball", s1: "base", s2: "ball"},
  { word: "number", s1: "num", s2: "ber"},
  { word: "napkin", s1: "nap", s2: "kin"},
  { word: "zipper", s1: "zip", s2: "per"},
  { word: "winter", s1: "win", s2: "ter"},
  { word: "popcorn", s1: "pop", s2: "corn"},
  { word: "summer", s1: "sum", s2: "mer"},
  { word: "hallway", s1: "hall", s2: "way"},
  { word: "people", s1: "peo", s2: "ple"},
  { word: "jacket", s1: "jack", s2: "et"},
  { word: "earring", s1: "ear", s2: "ring"},
  { word: "father", s1: "fat", s2: "her"},
  { word: "birthday", s1: "birth", s2: "day"},
  { word: "study", s1: "stu", s2: "dy"},
  { word: "purple", s1: "pur", s2: "ple"},
  { word: "honey", s1: "hon", s2: "ey"},
  { word: "student", s1: "stu", s2: "dent"},
  { word: "princess", s1: "prin", s2: "cess"},
  { word: "pumpkin", s1: "pump", s2: "kin"},
  { word: "science", s1: "sci", s2: "ence"},
  { word: "music", s1: "mus", s2: "ic"},
  { word: "teddy", s1: "ted", s2: "dy"},
  { word: "water", s1: "wa", s2: "ter"},
  { word: "ladder", s1: "lad", s2: "der"},
  { word: "toothbrush", s1: "tooth", s2: "brush"},
  { word: "tissue", s1: "tiss", s2: "ue"},
  { word: "table", s1: "ta", s2: "ble"},
  { word: "backpack", s1: "back", s2: "pack"},
  { word: "binder", s1: "bin", s2: "der"},
  { word: "coffee", s1: "coff", s2: "ee"},
  { word: "taco", s1: "ta", s2: "co"},
  { word: "hockey", s1: "hock", s2: "ey"},
  { word: "letter", s1: "let", s2: "ter"},
  { word: "towel", s1: "tow", s2: "el"},
  { word: "balloon", s1: "ba", s2: "lloon"},
  { word: "pizza", s1: "piz", s2: "za"},
  { word: "baby", s1: "ba", s2: "by"},
  { word: "snowflake", s1: "snow", s2: "flake"},
  { word: "firetruck", s1: "fire", s2: "truck"},
  { word: "bacon", s1: "ba", s2: "con"},
  { word: "bunny", s1: "bun", s2: "ny"},
  { word: "neighbor", s1: "neigh", s2: "bor"},
  { word: "sleeping", s1: "sleep", s2: "ing"},
  { word: "surprise", s1: "sur", s2: "prise"},
  { word: "sandwich", s1: "sand", s2: "wich"},
  { word: "farmer", s1: "far", s2: "mer"},
  { word: "Monday", s1: "Mon", s2: "day"},
  { word: "reading", s1: "read", s2: "ing"},
  { word: "forehead", s1: "fore", s2: "head"},
  { word: "weekend", s1: "week", s2: "end"},
  { word: "shampoo", s1: "sham", s2: "poo"},
  { word: "address", s1: "add", s2: "ress"},
  { word: "grandma", s1: "grand", s2: "ma"},
  { word: "thursday", s1: "thurs", s2: "day"},
  { word: "dinner", s1: "din", s2: "ner"},
  { word: "breakfast", s1: "break", s2: "fast"},
  { word: "pepper", s1: "pep", s2: "per"},
  { word: "closet", s1: "clo", s2: "set"},
  { word: "friday", s1: "fri", s2: "day"},
  { word: "finger", s1: "fin", s2: "ger"},
  { word: "tinfoil", s1: "tin", s2: "foil"},
  { word: "april", s1: "a", s2: "pril"},
  { word: "oval", s1: "ov", s2: "al"},
  { word: "cherry", s1: "ch", s2: "erry"},
  { word: "question", s1: "quest", s2: "ion"},
  { word: "bathroom", s1: "bath", s2: "room"},
  { word: "airplane", s1: "air", s2: "plane"},
  { word: "perfect", s1: "per", s2: "fect"},
  { word: "thousand", s1: "thous", s2: "and"},
  { word: "country", s1: "count", s2: "ry"},
  { word: "freedom", s1: "free", s2: "dom"},
  { word: "husband", s1: "hus", s2: "band"},
];

let words2 = [
  { word: "ladybug",s1: "la",s2: "dy",s3: "bug"},
  { word: "triangle",s1: "tri",s2: "an",s3: "gle"},
  { word: "newspaper",s1: "news",s2: "pa",s3: "per"},
  { word: "sunflower",s1: "sun",s2: "fl",s3: "ower"},
  { word: "elephant",s1: "el",s2: "e",s3: "phant"},
  { word: "raspberry",s1: "rasp",s2: "ber",s3: "ry"},
  { word: "bulldozer",s1: "bull",s2: "doz",s3: "er"},
  { word: "detective",s1: "de",s2: "tec",s3: "tive"},
  { word: "apricot",s1: "ap",s2: "ri",s3: "cot"},
  { word: "astronaut",s1: "as",s2: "tro",s3: "naut"},
  { word: "eleven",s1: "e",s2: "lev",s3: "en"},
  { word: "saturday",s1: "sat",s2: "ur",s3: "day"},
  { word: "tomorrow",s1: "to",s2: "mor",s3: "row"},
  { word: "hamburger",s1: "ham",s2: "bur",s3: "ger"},
  { word: "coloring",s1: "col",s2: "or",s3: "ing"},
  { word: "tomato",s1: "to",s2: "mat",s3: "o"},
  { word: "telephone",s1: "tel",s2: "e",s3: "phone"},
  { word: "gigantic",s1: "gi",s2: "gan",s3: "tic"},
  { word: "camera",s1: "cam",s2: "er",s3: "a"},
  { word: "video",s1: "vid",s2: "e",s3: "o"},
  { word: "magazine",s1: "mag",s2: "a",s3: "zine"},
  { word: "president",s1: "pres",s2: "i",s3: "dent"},
  { word: "beautiful",s1: "beaut",s2: "i",s3: "ful"},
  { word: "library",s1: "li",s2: "brar",s3: "y"},
  { word: "afternoon",s1: "af",s2: "ter",s3: "noon"},
  { word: "pajama",s1: "pa",s2: "jam",s3: "a"},
  { word: "december",s1: "de",s2: "cem",s3: "ber"},
  { word: "basketball",s1: "bas",s2: "ket",s3: "ball"},
  { word: "banana",s1: "ba",s2: "nan",s3: "a"},
  { word: "vacation",s1: "va",s2: "ca",s3: "tion"},
  { word: "october",s1: "oc",s2: "tob",s3: "er"},
  { word: "celery",s1: "cel",s2: "er",s3: "y"},
  { word: "cucumber",s1: "cu",s2: "cum",s3: "ber"},
  { word: "underwear",s1: "un",s2: "der",s3: "wear"},
  { word: "butterfly",s1: "but",s2: "ter",s3: "fly"},
  { word: "computer",s1: "com",s2: "pu",s3: "ter"},
  { word: "umbrella",s1: "um",s2: "bre",s3: "lla"},
  { word: "fingerpaint",s1: "fin",s2: "ger",s3: "paint"},
  { word: "strawberry",s1: "st",s2: "raw",s3: "berry"},
  { word: "octopus",s1: "oc",s2: "to",s3: "pus"},
  { word: "broccoli",s1: "br",s2: "occ",s3: "oli"},
  { word: "dinosaur",s1: "di",s2: "no",s3: "saur"},
  { word: "dishwasher",s1: "dish",s2: "wash",s3: "er"},
  { word: "spaghetti",s1: "spa",s2: "ghet",s3: "ti"},
  { word: "ponytail",s1: "po",s2: "ny",s3: "tail"},
  { word: "bicycle",s1: "bi",s2: "cyc",s3: "le"},
  { word: "dangerous",s1: "da",s2: "nger",s3: "ous"},
  { word: "government",s1: "gov",s2: "ern",s3: "ment"},
  { word: "lemonade",s1: "lem",s2: "on",s3: "ade"},
  { word: "disrespect",s1: "dis",s2: "re",s3: "spect"},
  { word: "disagree",s1: "dis",s2: "ag",s3: "ree"},
  { word: "rectangle",s1: "rec",s2: "tang",s3: "le"},
  { word: "tradition",s1: "tra",s2: "di",s3: "tion"},
  { word: "reflection",s1: "re",s2: "flec",s3: "tion"},
  { word: "container",s1: "con",s2: "tain",s3: "er"},
  { word: "refreshment",s1: "re",s2: "fresh",s3: "ment"},
  { word: "employment",s1: "em",s2: "ploy",s3: "ment"},
  { word: "paragraph",s1: "par",s2: "a",s3: "graph"},
  { word: "family",s1: "fam",s2: "il",s3: "y"},
  { word: "chocolate",s1: "choc",s2: "o",s3: "late"},
  { word: "piano",s1: "pi",s2: "an",s3: "o"},
  { word: "animal",s1: "an",s2: "i",s3: "mal"},
  { word: "blueberry",s1: "blue",s2: "berr",s3: "y"},
  { word: "celebrate",s1: "cel",s2: "eb",s3: "rate"},
  { word: "history",s1: "his",s2: "tor",s3: "y"},
  { word: "holiday",s1: "hol",s2: "i",s3: "day"},
  { word: "envelope",s1: "en",s2: "vel",s3: "ope"},
  { word: "pollution",s1: "po",s2: "llu",s3: "tion"},
  { word: "calendar",s1: "cal",s2: "en",s3: "dar"},
  { word: "halloween",s1: "hall",s2: "o",s3: "ween"},
  { word: "pineapple",s1: "pine",s2: "app",s3: "le"},
  { word: "adjective",s1: "ad",s2: "jec",s3: "tive"},
  { word: "volleyball",s1: "vol",s2: "ley",s3: "ball"},
  { word: "hospital",s1: "hos",s2: "pi",s3: "tal"},
  { word: "piggybank",s1: "pig",s2: "gy",s3: "bank"},
  { word: "policeman",s1: "po",s2: "lice",s3: "man"},
  { word: "tortilla",s1: "tort",s2: "i",s3: "lla"},
  { word: "screwdriver",s1: "screw",s2: "dri",s3: "ver"},
  { word: "fingernail",s1: "fin",s2: "ger",s3: "nail"},
  { word: "vitamin",s1: "vi",s2: "ta",s3: "min"},
  { word: "sandwiches",s1: "sand",s2: "wich",s3: "es"},
  { word: "handwriting",s1: "hand",s2: "writ",s3: "ing"},
  { word: "november",s1: "no",s2: "vem",s3: "ber"},
  { word: "barbeque",s1: "barb",s2: "e",s3: "que"},
  { word: "grandfather",s1: "grand",s2: "fa",s3: "ther"},
  { word: "principal",s1: "princ",s2: "i",s3: "pal"},
  { word: "popsicle",s1: "pop",s2: "si",s3: "cle"},
  { word: "applesauce",s1: "app",s2: "le",s3: "sauce"},
  { word: "blueberries",s1: "blue",s2: "berr",s3: "ies"},
  { word: "tablecloth",s1: "ta",s2: "ble",s3: "cloth"},
  { word: "instrument",s1: "in",s2: "str",s3: "ument"},
  { word: "daffodil",s1: "daff",s2: "o",s3: "dil"},
  { word: "multiply",s1: "mul",s2: "ti",s3: "ply"},
  { word: "reporter",s1: "re",s2: "port",s3: "er"},
  { word: "calculate",s1: "cal",s2: "cu",s3: "late"},
  { word: "opinion",s1: "o",s2: "pin",s3: "ion"},
  { word: "forgetful",s1: "for",s2: "get",s3: "ful"},
  { word: "character",s1: "cha",s2: "rac",s3: "ter"},
  { word: "kangaroo",s1: "kan",s2: "ga",s3: "roo"},
  { word: "understand",s1: "un",s2: "der",s3: "stand"},
  { word: "Africa",s1: "Afr",s2: "ic",s3: "a"},
  { word: "favorite",s1: "fav",s2: "or",s3: "ite"},
  { word: "consonant",s1: "con",s2: "so",s3: "nant"},
  { word: "syllable",s1: "syl",s2: "la",s3: "ble"},
  { word: "memory",s1: "mem",s2: "o",s3: "ry"},
  { word: "mystery",s1: "mys",s2: "ter",s3: "y"},
  { word: "happiness",s1: "hap",s2: "pi",s3: "ness"},
  { word: "potato",s1: "po",s2: "ta",s3: "to"},
];
